[17:02:33.619] Running build in Washington, D.C., USA (East) – iad1
[17:02:33.619] Build machine configuration: 4 cores, 8 GB
[17:02:33.634] Cloning github.com/torvus-security/torvus-website (Branch: main, Commit: 4f51605)
[17:02:33.937] Cloning completed: 303.000ms
[17:02:35.047] Restored build cache from previous deployment (7xKpHX7GVWcxk8ESUEANUYceYwqQ)
[17:02:35.506] Running "vercel build"
[17:02:35.938] Vercel CLI 47.1.1
[17:02:36.270] Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
[17:02:36.271] Using pnpm@10.x based on project creation date
[17:02:36.271] To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
[17:02:36.282] Installing dependencies...
[17:02:36.899] Lockfile is up to date, resolution step is skipped
[17:02:36.957] Already up to date
[17:02:37.104] 
[17:02:37.122] Done in 728ms using pnpm v10.15.1
[17:02:37.132] Detected Next.js version: 14.2.16
[17:02:37.138] Running "pnpm run build"
[17:02:37.448] 
[17:02:37.448] > torvus-www@0.1.0 build /vercel/path0
[17:02:37.448] > next build
[17:02:37.448] 
[17:02:38.178]   ▲ Next.js 14.2.16
[17:02:38.178] 
[17:02:38.253]    Creating an optimized production build ...
[17:02:50.076]  ✓ Compiled successfully
[17:02:50.077]    Linting and checking validity of types ...
[17:02:54.117] Failed to compile.
[17:02:54.117] 
[17:02:54.117] ./components/feature-grid.tsx:107:9
[17:02:54.117] Type error: Type '{ children: Element[]; open: boolean; title: string; icon: Element | null; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & Props'.
[17:02:54.117]   Property 'icon' does not exist on type 'IntrinsicAttributes & Props'.
[17:02:54.117] 
[17:02:54.117] [0m [90m 105 |[39m         open[33m=[39m{[33m![39m[33m![39mactive}[0m
[17:02:54.117] [0m [90m 106 |[39m         title[33m=[39m{active[33m?[39m[33m.[39mtitle [33m?[39m[33m?[39m [32m""[39m}[0m
[17:02:54.117] [0m[31m[1m>[22m[39m[90m 107 |[39m         icon[33m=[39m{[0m
[17:02:54.117] [0m [90m     |[39m         [31m[1m^[22m[39m[0m
[17:02:54.118] [0m [90m 108 |[39m           active [33m?[39m ([0m
[17:02:54.118] [0m [90m 109 |[39m             [33m<[39m[33mspan[39m className[33m=[39m{[32m`mt-0.5 inline-flex h-9 w-9 items-center justify-center rounded-full ring-1 ${active.tint}`[39m}[33m>[39m[0m
[17:02:54.118] [0m [90m 110 |[39m               [33m<[39m[33mactive[39m[33m.[39m[33mIcon[39m className[33m=[39m[32m"h-5 w-5"[39m [33m/[39m[33m>[39m[0m
[17:02:54.160]  ELIFECYCLE  Command failed with exit code 1.
[17:02:54.179] Error: Command "pnpm run build" exited with 1